import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { CardGrid, ContactButtons, Eyebrow, FaqAccordion, RelatedCard, SectionHeading, type ServiceCard, type ServiceFaq } from "@/components/ServicePage";
import { getServiceNavigation } from "@/data/services";
import { business } from "@/data/business";

const title = "Vehicle Winch Recovery Solutions for Every Situation";
const description = "Ensure safe and efficient vehicle recovery with expert-recommended winches. Find the right fit for you!";
const path = "/services/winch-out";

export const metadata: Metadata = {
  title: { absolute: title }, description,
  alternates: { canonical: path }, robots: { index: true, follow: true },
  openGraph: { title, description, url: path, type: "website", siteName: business.name, images: [{ url: "/images/service-winch.jpg", alt: "Professional vehicle winch-out assistance" }] },
  twitter: { card: "summary_large_image", title, description, images: ["/images/service-winch.jpg"] },
};

const situations: ServiceCard[] = [
  { icon: "fa-solid fa-water", title: "Vehicle Stuck in Mud", text: "Mud can quickly reduce traction and allow wheels to sink deeper. Professional winching may help move the vehicle back towards firmer ground." },
  { icon: "fa-solid fa-seedling", title: "Wet or Soft Grass", text: "Saturated grass can become extremely slippery, leaving a vehicle unable to gain enough grip to move." },
  { icon: "fa-solid fa-mound", title: "Soft Ground", text: "Loose or waterlogged ground can give way beneath a vehicle's weight and leave the wheels unable to generate traction." },
  { icon: "fa-solid fa-gauge", title: "Loss of Traction", text: "Sometimes the vehicle itself is working normally but cannot move because the tyres cannot grip the surface." },
  { icon: "fa-solid fa-road", title: "Awkward Roadside Position", text: "A vehicle that has moved away from a firm road surface may require controlled extraction before it can safely continue." },
  { icon: "fa-solid fa-mountain", title: "Uneven Ground", text: "Where access and conditions allow, professional winching may help reposition a vehicle immobilised on difficult or uneven ground." },
];
const included: ServiceCard[] = [
  { icon: "fa-solid fa-location-crosshairs", title: "Location Assessment", text: "The vehicle's position and surrounding area are considered before recovery begins." },
  { icon: "fa-solid fa-magnifying-glass", title: "Ground Condition Review", text: "Mud, soft grass, loose ground and other surfaces can affect how the vehicle should be extracted." },
  { icon: "fa-solid fa-toolbox", title: "Suitable Recovery Equipment", text: "Professional recovery equipment is used based on the vehicle and circumstances." },
  { icon: "fa-solid fa-arrows-left-right", title: "Controlled Winching", text: "The vehicle is moved in a controlled way towards a safer or more stable position where appropriate." },
  { icon: "fa-solid fa-car-side", title: "Cars & Light Vans", text: "Winch-out assistance may be available for common passenger cars and suitable light vans." },
  { icon: "fa-solid fa-truck-ramp-box", title: "Recovery if Required", text: "If the vehicle cannot safely continue after extraction, further vehicle recovery can be arranged." },
];
const benefits: ServiceCard[] = [
  { icon: "fa-solid fa-clock", title: "Available 24/7", text: "Vehicle recovery problems can happen at any time, so our roadside and recovery assistance is available around the clock." },
  { icon: "fa-solid fa-arrows-to-circle", title: "Controlled Extraction", text: "The aim is to move the vehicle using a controlled recovery approach rather than forcing it free." },
  { icon: "fa-solid fa-toolbox", title: "Professional Equipment", text: "Suitable recovery equipment is used based on the vehicle and situation." },
  { icon: "fa-solid fa-van-shuttle", title: "Cars & Suitable Vans", text: "Winch-out assistance may be available for common passenger cars and suitable light vans." },
  { icon: "fa-solid fa-truck-pickup", title: "Recovery Available", text: "If the vehicle cannot safely continue after extraction, breakdown recovery can be discussed." },
  { icon: "fa-solid fa-map-location-dot", title: "Local Support", text: "Based in Darlington, FSR Recovery Group provides roadside and vehicle recovery services across Darlington and surrounding areas." },
];
const faqs: ServiceFaq[] = [
  ["What is a vehicle winch-out service?", "A vehicle winch-out service uses professional recovery equipment to help extract a vehicle that cannot move from its current position under its own power."],
  ["Can you help if my car is stuck in mud?", "Where the vehicle and location can be accessed safely, professional winching may be suitable for extracting a car that has become stuck in mud. Contact us with your location and details so the situation can be assessed."],
  ["Can you help with a vehicle stuck on wet grass?", "Yes, depending on the position, access and ground conditions. Wet or soft grass can reduce traction enough to leave a vehicle unable to move."],
  ["Do you provide winch-out assistance 24/7?", "FSR Recovery Group provides 24/7 roadside and vehicle recovery assistance. Contact us with the details of the situation so availability and requirements can be discussed."],
  ["What information should I provide when calling?", "Tell us your exact location, vehicle make and model, what the vehicle is stuck in and anything important about access or surrounding ground conditions."],
  ["Should I keep trying to drive out of mud?", "Repeated wheel spinning can sometimes cause a vehicle to dig deeper into soft ground. If the vehicle is firmly stuck, professional assistance may be more appropriate."],
  ["Can you winch out vans?", "Winch-out assistance may be available for suitable light vans depending on their size, position, access and recovery conditions."],
  ["Can you recover a vehicle from a ditch?", "Some positions may be suitable for controlled extraction, while others may require different equipment or additional safety measures. The location and circumstances need to be assessed before recovery can be confirmed."],
  ["What happens if my vehicle is damaged after becoming stuck?", "If the vehicle cannot safely continue after extraction, FSR Recovery Group can discuss vehicle breakdown recovery to an agreed destination."],
  ["Do you offer winch-out services in Darlington?", "Yes. FSR Recovery Group is based in Darlington and provides vehicle recovery services across Darlington and surrounding areas. Contact us with your location to confirm availability."],
  ["How much does a winch-out cost?", "The cost depends on factors such as the vehicle, location, accessibility, ground conditions and complexity of the recovery. Call or WhatsApp us with the details so an appropriate quote can be discussed."],
].map(([question, answer]) => ({ question, answer }));

const schema = { "@context": "https://schema.org", "@graph": [
  { "@type": "Service", name: "Vehicle Winch Out Service", description, serviceType: "Vehicle winch out service", provider: { "@type": "LocalBusiness", name: business.name, telephone: business.phone, address: { "@type": "PostalAddress", streetAddress: business.address.street, addressLocality: business.address.locality, postalCode: business.address.postalCode, addressCountry: business.address.countryCode } }, areaServed: { "@type": "City", name: "Darlington" }, availableChannel: { "@type": "ServiceChannel", servicePhone: { "@type": "ContactPoint", telephone: business.phone, contactType: "customer service", availableLanguage: "English" } } },
  { "@type": "FAQPage", mainEntity: faqs.map(({ question, answer }) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) }
] };

export default function WinchOutPage() {
  return <><Header activePath="/services" /><main>
    <section className="service-hero relative isolate min-h-[680px] overflow-hidden bg-navy text-white">
      <Image src="/images/service-winch.jpg" alt="Professional vehicle winch-out assistance" fill priority sizes="100vw" className="-z-20 object-cover" />
      <div className="absolute inset-0 -z-10 bg-gradient-to-r from-navy via-navy/90 to-navy/30" />
      <div className="container-site flex min-h-[680px] items-center py-20"><div className="fade-up max-w-3xl"><Eyebrow>24/7 Vehicle Extraction</Eyebrow><h1 className="text-4xl font-extrabold leading-[1.08] sm:text-5xl lg:text-7xl">Professional Winch Out Service for Stuck Vehicles</h1><p className="my-6 max-w-2xl text-lg leading-8 text-white/80">When your car or van becomes stuck and cannot move under its own power, forcing it free can make the situation worse. FSR Recovery Group provides professional winch-out assistance for suitable vehicles stuck in mud, soft ground or other difficult positions.</p><ContactButtons dark callLabel={`Call ${business.phoneDisplay}`} whatsappLabel="WhatsApp for Winch-Out Help" /><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm font-bold">{["Available 24/7", "Professional Winching", "Cars & Suitable Vans"].map(x=><span key={x}><i className="fa-solid fa-circle-check mr-2 text-red" />{x}</span>)}</div></div></div>
    </section>

    <section className="py-16 sm:py-24"><div className="container-site grid items-center gap-10 lg:grid-cols-2 lg:gap-16"><div className="fade-up relative min-h-[430px] overflow-hidden rounded-3xl"><Image src="/images/gallery-3.jpg" alt="Vehicle extraction using winching equipment" fill sizes="(min-width: 1024px) 50vw, 100vw" className="object-cover" /></div><div className="fade-up"><Eyebrow>Controlled Vehicle Extraction</Eyebrow><h2 className="mb-5 text-3xl font-extrabold sm:text-4xl">Safe Help When Your Vehicle Is Stuck</h2><div className="space-y-4 leading-7 text-navy/70"><p>A vehicle can become stuck surprisingly quickly. Wet grass, mud, soft ground or an awkward position can leave the wheels spinning without enough traction to move safely.</p><p>FSR Recovery Group provides professional winch-out assistance for suitable cars and light vans that cannot free themselves under their own power.</p><p>Before extraction, the vehicle position, surrounding ground and access need to be considered. The aim is to move the vehicle in a controlled way towards a safer and more stable position.</p><p>If the vehicle is damaged or cannot safely continue after extraction, professional <Link href="/services/vehicle-breakdown-recovery" className="font-bold text-red underline">breakdown recovery</Link> can also be discussed.</p></div><a href={business.tel} className="mt-7 block rounded-2xl border-l-4 border-red bg-navy p-5 font-bold text-white">Vehicle stuck now? <span className="text-red">Call {business.phoneDisplay}</span> for winch-out assistance.</a></div></div></section>

    <section className="bg-slate-50 py-16 sm:py-24"><div className="container-site"><SectionHeading eyebrow="When You May Need Us" title="Winch-Out Situations We Can Help With" intro="Different surfaces and positions can leave a vehicle unable to move even when it is otherwise working normally. Professional winching may provide the right way to extract it." /><CardGrid cards={situations} /><p className="mt-7 text-center text-sm text-navy/60">All winch-out work is subject to safe access, vehicle position, ground conditions and operator assessment.</p></div></section>

    <section className="relative isolate overflow-hidden bg-navy py-20 text-white sm:py-28"><Image src="/images/gallery-2.jpg" alt="Night-time stuck vehicle recovery assistance" fill sizes="100vw" className="-z-20 object-cover" /><div className="absolute inset-0 -z-10 bg-navy/90"/><div className="container-site"><div className="fade-up max-w-2xl"><Eyebrow>Day or Night</Eyebrow><h2 className="text-3xl font-extrabold sm:text-5xl">24-Hour Winch-Out Assistance</h2><div className="my-6 space-y-4 leading-7 text-white/75"><p>A vehicle can become stuck at any time, whether you are leaving a property early in the morning, travelling in poor weather or dealing with an unexpected situation late at night.</p><p>FSR Recovery Group provides 24/7 roadside and recovery assistance, including vehicle winching where the location and conditions allow safe extraction.</p><p>When contacting us, provide your exact location, vehicle details and a short description of what the vehicle is stuck in. Photos or a location pin may also be useful where it is safe to provide them.</p></div><ContactButtons dark callLabel="Call for Winch-Out Assistance" whatsappLabel="WhatsApp Your Location" /></div></div></section>

    <section className="py-16 sm:py-24"><div className="container-site"><SectionHeading eyebrow="Professional Extraction Support" title="What Our Winch-Out Service Includes" intro="Our vehicle winching service is designed to assess the situation and use suitable recovery equipment to help extract a stuck vehicle where safe access is possible." /><CardGrid cards={included} /></div></section>

    <section className="bg-navy py-16 text-white sm:py-24"><div className="container-site"><div className="[&_h2]:!text-white"><SectionHeading eyebrow="Simple Process" title="How Vehicle Winch-Out Assistance Works" /></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{[["01","Contact Us","Call or WhatsApp FSR Recovery Group and explain that your vehicle is stuck."],["02","Share the Details","Provide your location, vehicle make/model and tell us what the vehicle is stuck in or how it is positioned."],["03","Situation Is Assessed","The vehicle position, access and ground conditions are considered before the appropriate extraction method is determined."],["04","Vehicle Is Extracted","Where conditions allow, suitable winching equipment is used to help move the vehicle towards stable ground."]].map(([n,t,x])=><article key={n} className="fade-up rounded-3xl border border-white/10 bg-white/[.06] p-6"><span className="text-4xl font-extrabold text-red">{n}</span><h3 className="mb-2 mt-5 text-xl font-bold">{t}</h3><p className="leading-7 text-white/70">{x}</p></article>)}</div><div className="mt-9 flex justify-center"><ContactButtons dark callLabel="Call Now" whatsappLabel="WhatsApp Your Location" /></div></div></section>

    <section className="bg-slate-50 py-16 sm:py-24"><div className="container-site"><SectionHeading eyebrow="Why Choose Us" title="Professional Winching for Difficult Situations" /><CardGrid cards={benefits} /></div></section>

    <section className="py-16 sm:py-24"><div className="container-site grid items-center gap-10 lg:grid-cols-2 lg:gap-16"><div className="fade-up"><Eyebrow>Local Vehicle Extraction</Eyebrow><h2 className="text-3xl font-extrabold sm:text-4xl">Winch-Out Assistance in Darlington and Surrounding Areas</h2><div className="my-6 space-y-4 leading-7 text-navy/70"><p>FSR Recovery Group is based at 135 Gladstone St, Darlington DL3 6LB and provides vehicle recovery and winch-out assistance across <Link href="/areas/darlington" className="font-semibold text-red">Darlington</Link> and surrounding areas.</p><p>If your car or van becomes stuck in mud, soft ground or another difficult but safely accessible position — including verges along the <Link href="/areas/a66" className="font-semibold text-red">A66</Link> — contact us with your location and details of the situation.</p><p>If you are outside Darlington, call or WhatsApp us with your location so we can confirm whether assistance is available.</p></div><address className="mb-7 rounded-2xl bg-slate-100 p-5 not-italic leading-7"><strong>{business.name}</strong><br/>{business.addressFull}<br/><a href={business.tel} className="font-bold text-red">{business.phoneDisplay}</a></address><div className="flex flex-col gap-3 sm:flex-row"><a href={business.tel} className="rounded-full bg-red px-6 py-3.5 text-center font-bold text-white">Call for Winch-Out Help</a><Link href="/areas" className="rounded-full border border-navy/20 px-6 py-3.5 text-center font-bold">View Areas Covered</Link></div></div><div className="fade-up relative min-h-[480px] overflow-hidden rounded-3xl"><Image src="/images/service-winch.jpg" alt="Car stuck in mud receiving recovery help" fill sizes="(min-width: 1024px) 50vw, 100vw" className="object-cover" /></div></div></section>

    <section className="bg-slate-50 py-16 sm:py-24"><div className="container-site"><SectionHeading eyebrow="Know the Next Step" title="Vehicle Extraction or Full Recovery?" /><div className="grid gap-6 lg:grid-cols-2">{[["Winch-Out Assistance","Winch-out assistance is suitable when a vehicle is stuck because of its position, ground conditions or lack of traction but may otherwise be capable of continuing once safely extracted.","The aim is to move the vehicle back onto stable ground where appropriate.","/images/service-winch.jpg","Controlled car winch out on difficult ground"],["Vehicle Breakdown Recovery","If the vehicle has been damaged, developed a fault or cannot safely continue after extraction, professional vehicle recovery may be required.","FSR Recovery Group can transport the vehicle to an agreed garage, home address or another suitable destination.","/images/service-breakdown.jpg","Vehicle prepared for full breakdown recovery"]].map(([t,a,b,img,alt])=><article key={t} className="fade-up overflow-hidden rounded-3xl bg-navy text-white"><div className="relative h-64"><Image src={img} alt={alt} fill sizes="(min-width: 1024px) 50vw, 100vw" className="object-cover" /></div><div className="p-7"><h3 className="mb-3 text-2xl font-bold">{t}</h3><p className="mb-3 leading-7 text-white/70">{a}</p><p className="leading-7 text-white/70">{b}</p></div></article>)}</div><div className="mt-9 flex flex-col items-center justify-center gap-3 sm:flex-row"><a href={business.tel} className="rounded-full bg-red px-7 py-4 font-bold text-white">Request Winch-Out Assistance</a><Link href="/services/vehicle-breakdown-recovery" className="rounded-full border border-navy/20 px-7 py-4 font-bold text-navy">View 24/7 Vehicle Breakdown Recovery</Link></div></div></section>

    <section className="bg-navy py-16 text-white sm:py-24"><div className="container-site"><div className="[&_h2]:!text-white"><SectionHeading eyebrow="More Ways We Can Help" title="Related Roadside & Recovery Services" /></div><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4"><RelatedCard title="24/7 Vehicle Breakdown Recovery" text="Professional recovery when a vehicle cannot safely continue after a breakdown or extraction." href={getServiceNavigation("vehicle-breakdown-recovery").href} icon="fa-solid fa-truck-pickup"/><RelatedCard title="Roadside Assistance" text="Professional help for suitable vehicle problems at your current location." href={getServiceNavigation("roadside-assistance").href} icon="fa-solid fa-screwdriver-wrench"/><RelatedCard title="Accident Emergency Assistance" text="Vehicle recovery support following a collision or road traffic incident." href={getServiceNavigation("accident-emergency-assistance").href} icon="fa-solid fa-car-burst"/><RelatedCard title="Vehicle Transporting" text="Safe transportation when a vehicle needs moving between agreed locations." href={getServiceNavigation("vehicle-transporting").href} icon="fa-solid fa-truck-ramp-box"/></div><div className="mt-9 flex justify-center gap-6"><Link href="/services" className="font-bold text-white underline decoration-red decoration-2 underline-offset-4">View All Services</Link><Link href="/contact" className="font-bold text-white underline decoration-red decoration-2 underline-offset-4">Contact Us</Link></div></div></section>

    <section className="bg-slate-50 py-16 sm:py-24"><div className="container-site"><SectionHeading eyebrow="Common Questions" title="Winch Out FAQs" /><FaqAccordion faqs={faqs} /></div></section>

    <section className="relative isolate overflow-hidden bg-navy py-20 text-white sm:py-28"><Image src="/images/service-winch.jpg" alt="Stuck vehicle recovery assistance" fill sizes="100vw" className="-z-20 object-cover"/><div className="absolute inset-0 -z-10 bg-navy/90"/><div className="container-site fade-up text-center"><Eyebrow>Vehicle Stuck?</Eyebrow><h2 className="text-3xl font-extrabold sm:text-5xl">Get Professional Winch-Out Assistance</h2><p className="mx-auto my-6 max-w-3xl text-lg leading-8 text-white/75">If your car or van is stuck and cannot regain traction, contact FSR Recovery Group. Tell us where you are, what vehicle you have and what it is stuck in so we can discuss the recovery you need.</p><div className="flex justify-center"><ContactButtons dark callLabel={`Call ${business.phoneDisplay}`} whatsappLabel="WhatsApp Your Location" /></div><address className="mt-8 not-italic leading-7 text-white/75"><strong className="text-white">{business.name}</strong><br/>{business.addressFull}<br/><a href={business.tel}>{business.phoneDisplay}</a></address></div></section>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, "\\u003c") }} />
  </main><Footer /></>;
}
