import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { business } from "@/data/business";

export const metadata: Metadata = {
  title: { absolute: "FSR Recovery Group: Terms & Conditions Guide" },
  description: "Explore the terms and conditions of FSR Recovery Group. Get clarity on your agreement with us now.",
  alternates: { canonical: "/terms-and-conditions" },
};

const sections = [
  ["1. About these terms", <p key="p">These terms apply when you request roadside assistance, vehicle recovery, winch-out assistance or vehicle transport from FSR Recovery Group. Please read them before confirming a service. Nothing in these terms affects rights that you have under applicable UK consumer law.</p>],
  ["2. Contact details", <p key="p">FSR Recovery Group can be contacted at {business.addressFull}, by telephone on <a href={business.tel}>{business.phoneDisplay}</a>, or by email at <a href={`mailto:${business.email}`}>{business.email}</a>.</p>],
  ["3. Service requests and acceptance", <><p>Contacting us is a request for assistance and does not by itself guarantee that a job can be accepted. We may need your location, vehicle details, description of the issue, access information and intended destination before confirming whether assistance is available.</p><p>A service is agreed when we confirm that we can undertake the work and you accept the service details and any quote provided. Availability remains subject to safe access, suitable equipment, vehicle condition, location and circumstances.</p></>],
  ["4. Quotes and payment", <><p>Prices or estimates are based on the information available when they are provided. Tell us promptly if the vehicle, location, destination, access or circumstances differ from what was described, as this may affect the work required and the price.</p><p>We will explain the applicable charge and accepted payment arrangements when the service is discussed. You are responsible for paying charges you have agreed, unless another person or organisation has expressly accepted responsibility for payment.</p></>],
  ["5. Your responsibilities", <><p>You must provide information that is accurate to the best of your knowledge, including the vehicle&apos;s location, condition, dimensions where relevant, access restrictions and any known damage or hazards. You must have authority to request work on the vehicle and identify a lawful, suitable collection and destination point.</p><p>Follow reasonable safety instructions, keep away from recovery equipment and do not interfere while work is underway. Remove or secure valuables and personal belongings where reasonably possible.</p></>],
  ["6. Safety and service limitations", <p key="content">We may pause, alter or decline work where access, traffic, weather, terrain, vehicle condition, instructions from authorities or another circumstance makes the proposed service unsafe, unlawful or unsuitable. Winch-out and roadside work is subject to an on-site assessment; extraction, repair or a successful restart cannot be guaranteed.</p>],
  ["7. Delays and events outside our control", <p key="content">Arrival and completion times are estimates unless expressly agreed otherwise. Traffic, weather, road closures, emergency incidents, availability of suitable equipment and other events outside our reasonable control may cause delay. We will seek to keep you informed where reasonably possible.</p>],
  ["8. Vehicle condition and belongings", <p key="content">Tell us about existing damage, modifications, mechanical defects, security systems or other matters that may affect handling. We are not responsible for pre-existing faults or damage, or for loss of unsecured personal items, except where responsibility cannot lawfully be excluded.</p>],
  ["9. Cancellation", <p key="content">If you need to cancel, contact us as soon as possible. We will tell you before confirmation if a particular booking has cancellation terms or if reasonable costs may arise after a vehicle or operator has been dispatched. Any statutory cancellation rights that apply to you remain unaffected.</p>],
  ["10. Liability", <><p>We are responsible for foreseeable loss or damage caused by our failure to use reasonable care and skill or by our breach of these terms. We are not responsible for loss that was not foreseeable, was caused by inaccurate or incomplete information, arose from a pre-existing defect, or could not reasonably have been avoided.</p><p>Nothing in these terms excludes or limits liability where it would be unlawful to do so, including liability for death or personal injury caused by negligence, fraud or fraudulent misrepresentation, or your statutory consumer rights.</p></>],
  ["11. Complaints", <p key="content">If you are dissatisfied, contact us promptly with your name, contact details, vehicle details, date and location of the service, and an explanation of the issue. We will review the information and respond as soon as reasonably practicable.</p>],
  ["12. General", <><p>If a court finds part of these terms unlawful, the remaining terms will continue to apply. A delay in enforcing a right does not waive that right. These terms are between you and FSR Recovery Group; no other person has a right to enforce them unless the law provides otherwise.</p><p>These terms are governed by the law of England and Wales. The courts that may hear a dispute will be determined by applicable law, including the protections available to consumers in the part of the UK where they live.</p></>],
  ["13. Changes to these terms", <p key="p">We may update these terms to reflect changes to our services, practices or legal obligations. The version published on this page applies from its stated update date.</p>],
] as const;

export default function TermsAndConditionsPage() {
  return <><Header /><main>
    <section className="relative isolate overflow-hidden text-white"><Image src="/images/service-roadside.webp" alt="Technician checking a car engine roadside in the rain" fill preload fetchPriority="high" sizes="100vw" className="-z-20 object-cover" /><div className="absolute inset-0 -z-10" style={{ background: "linear-gradient(90deg, rgba(11, 34, 65, 0.95), rgba(11, 34, 65, 0.8))" }} /><div className="container-site fade-up py-10 text-center sm:py-14 lg:py-20"><p className="mb-4 font-bold text-red-100">Legal Information</p><h1 className="text-3xl font-extrabold sm:text-4xl lg:text-6xl">Terms &amp; Conditions</h1><p className="mx-auto mt-5 max-w-2xl text-white/80">The terms that apply when you request our roadside, recovery or vehicle transport services.</p></div></section>
    <section className="bg-slate-50 py-16 sm:py-24"><div className="container-site"><div className="mx-auto max-w-4xl rounded-3xl border border-navy/10 bg-white p-6 shadow-sm sm:p-10 lg:p-12"><p className="mb-8 text-sm font-semibold text-navy/70">Last updated: 26 August 2026</p><div className="space-y-9">{sections.map(([title, content]) => <section key={title}><h2 className="mb-3 text-2xl font-extrabold text-navy">{title}</h2><div className="space-y-3 leading-7 text-navy/70 [&_a]:font-semibold [&_a]:text-red [&_a]:underline">{content}</div></section>)}</div><div className="mt-10 border-t border-navy/10 pt-7"><Link href="/contact" className="font-bold text-red underline">Contact FSR Recovery Group</Link></div></div></div></section>
  </main><Footer /></>;
}
